# https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Typescript Lint/Prettier

permissions:
  id-token: write
  contents: read

on: push

jobs:
  lint-prettier:
  runs-on: ubuntu-latest
  strategy:
    fail-fast: false
    matrix:
      node-version: ['18.x']

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies and build
        run: |
          npm ci
          npm run build
      - name: eslint check
        run: |
          npx eslint .
      - name: prettier check
        run: |
          npx prettier --check .
